### PR TITLE
Fixed multiline scenario bug and warning

### PR DESCRIPTION
**Pull request by incident-recipient**
This fixes the issue  **Feature/Scenario description can only be 1 line**

### CODE REVIEW

**Comment by bbqsrc** [comment]
Haha wow, that's one intense rule!

**Comment by bbqsrc** [comment]
Published in v0.8.4 :)

**Comment by ilslv** [comment]
@incident-recipient @bbqsrc I'm not sure why, but it looks like this PR somehow broke [cucumber-rust](https://github.com/bbqsrc/cucumber-rust) tests :man_shrugging:

**Comment by bbqsrc** [comment]
Not ideal this.

**Comment by bbqsrc** [comment]
@ilslv I've yanked 0.8.4. Issue is easily reproducable. Hopefully will have a solution this evening.

**Pull request merged**
